# Generated by Django 3.1.2 on 2021-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sum',
            name='input2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
